package repository

import (
	"context"
	"time"

	"go-backend-task/db/sqlc"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"
)

// UserRepository defines the database contract for managing User records.
// This interface separates our handlers/services from database technology choices.
type UserRepository interface {
	CreateUser(ctx context.Context, name string, dob time.Time) (sqlc.User, error)
	GetUserByID(ctx context.Context, id int32) (sqlc.User, error)
	UpdateUser(ctx context.Context, id int32, name string, dob time.Time) (sqlc.User, error)
	DeleteUser(ctx context.Context, id int32) error
	ListUsers(ctx context.Context, limit int32, offset int32) ([]sqlc.User, error)
}

// SQLCUserRepository implements UserRepository using code generated by SQLC.
type SQLCUserRepository struct {
	queries *sqlc.Queries
	db      *pgxpool.Pool
}

// NewUserRepository returns an instance of our SQLC repository.
func NewUserRepository(db *pgxpool.Pool) UserRepository {
	return &SQLCUserRepository{
		queries: sqlc.New(db),
		db:      db,
	}
}

// CreateUser inserts a new user record using SQLC.
func (r *SQLCUserRepository) CreateUser(ctx context.Context, name string, dob time.Time) (sqlc.User, error) {
	return r.queries.CreateUser(ctx, sqlc.CreateUserParams{
		Name: name,
		Dob:  pgtype.Date{Time: dob, Valid: true},
	})
}

// GetUserByID fetches a user by their unique primary key.
func (r *SQLCUserRepository) GetUserByID(ctx context.Context, id int32) (sqlc.User, error) {
	return r.queries.GetUserByID(ctx, id)
}

// UpdateUser modifies the details of an existing user record.
func (r *SQLCUserRepository) UpdateUser(ctx context.Context, id int32, name string, dob time.Time) (sqlc.User, error) {
	return r.queries.UpdateUser(ctx, sqlc.UpdateUserParams{
		ID:   id,
		Name: name,
		Dob:  pgtype.Date{Time: dob, Valid: true},
	})
}

// DeleteUser deletes a user from the system.
func (r *SQLCUserRepository) DeleteUser(ctx context.Context, id int32) error {
	return r.queries.DeleteUser(ctx, id)
}

// ListUsers queries multiple users with limit/offset pagination.
func (r *SQLCUserRepository) ListUsers(ctx context.Context, limit, offset int32) ([]sqlc.User, error) {
	return r.queries.ListUsers(ctx, sqlc.ListUsersParams{
		Limit:  limit,
		Offset: offset,
	})
}
